### ISSUE TITLE
Try to eliminate using "pow"

### ISSUE THREAD

**Issue by snoopyjc** [kevmuret/libhex#1]
"pow" is a very expensive call and your code would run much faster if you just compute the factor directly instead.

**Comment by kevmuret** [comment]
I made it, don't know about performance, i gonna completely remove math.h dependency, until it's still use floor function, but it's look like for this case it could be done easily. Just have to compute some things, here is the problem, reading value of `(int)((char*)&dd)[6]`  : 
Result      Read value > ...
1   |   -16
2   |   0
3   |   8
4   |   16
5   |   20
6   |   24
7   |   28
8   |   32
9   |   34
10  |   36
11  |   38
12  |   40
13  |   42
14  |   44
15  |   46

Before make a table i would like to find the calcul based solution, i things can be nice to know in  the future ;p.

**Comment by snoopyjc** [comment]
Yeah, I'll get to that one next.

Thanks for eliminating the expensive "pow" call, but you don't need to loop at
all.  Replace:

```
    if (po) {
        for (po, poi = 16; po > 1; --po) {
            poi *= 16;
        }
    } else {
        poi = 1;
    }
```

with:

poi = 1 << (po << 4);

I'll send you some more ideas!!  I used to optimize C code all the time back in
the day!

--joe

---- On Wed, 22 Oct 2014, kevmuret (notifications@github.com) wrote:

I made it, don't know about performance, i gonna completely remove math.h
dependency, until it's
still use floor function, but it's look like for this case it could be done
easily. Just have to
compute some things, here is the problem, reading value of
`(int)((char*)&dd)[6]`  : 
Result      Read value > ...
1   |   -16
2   |   0
3   |   8
4   |   16
5   |   20
6   |   24
7   |   28
8   |   32
9   |   34
10  |   36
11  |   38
12  |   40
13  |   42
14  |   44
15  |   46

Befroe make a table i would like to find the calcul based solution, i things can
be nice to know in 
the future ;p.

---

**Comment by snoopyjc** [comment]
Next optimization:  You can eliminate this:

int ishexchar (const int _c) {
    return ( (_c > 47 && _c < 58) || (_c > 64 && _c < 71) || (_c > 96 && *c < 103)
) ? 1 : 0;
};

Each "*c" above causes another memory fetch, and the whole thing can go away:

By declaring hex to be unsigned char *, (so all of the values are now in the
range [0..255],
changing mhexdec to be [256] and first filling it with "-1"s for all the values
(in a loop in
init_hexdec), then each time you pull a value out of it, just check it for "< 0"
and give an error
then and there.  Now delete the "ishexchar" call.

--joe

---- On Wed, 22 Oct 2014, kevmuret (notifications@github.com) wrote:

I made it, don't know about performance, i gonna completely remove math.h
dependency, until it's
still use floor function, but it's look like for this case it could be done
easily. Just have to
compute some things, here is the problem, reading value of
`(int)((char*)&dd)[6]`  : 
Result      Read value > ...
1   |   -16
2   |   0
3   |   8
4   |   16
5   |   20
6   |   24
7   |   28
8   |   32
9   |   34
10  |   36
11  |   38
12  |   40
13  |   42
14  |   44
15  |   46

Befroe make a table i would like to find the calcul based solution, i things can
be nice to know in 
the future ;p.

---

**Comment by snoopyjc** [comment]
Ok - using doubles and floor functions to convert an integer to hex is making me
crazy!

How about this?

char\* dechex (unsigned int dec) {
    char *hex = malloc(9, sizeof(char)) + 8;
        *hex = '\0';
        for(--hex; ; hex--) {
            *hex = mdechex[dec & 0xF];
            dec >>= 4;
            if(dec == 0) break;
        }
        return hex;
}

This may waste a couple bytes of memory, but it's probably not worth thinking
about.
If you like you can change it with a quick check to allocate a little less,
like:

```
   int size = 9;
   if((dec & 0xFFFF0000) == 0) size = 5;
   char *hex = malloc(size, sizeof(char)) + size-1;
```

malloc probably allocates in 4-bit chunks anyhow, so allocating 5 really
allocates 8, and allocating
9 really allocates 12, so maybe this would be better to see if it fits in 4 or 8
bytes (including the '\0'):

```
   int size = 9;
   if((dec & 0xF0000000) == 0) size = 8;
   if((dec & 0xFFFFF000) == 0) size = 4;
   char *hex = malloc(size, sizeof(char)) + size-1;
```

There is no reason to use calloc as we don't need the memory cleared.

Please test it as I'm just typing this into my mailer!!
--joe

---- On Wed, 22 Oct 2014, kevmuret (notifications@github.com) wrote:

I made it, don't know about performance, i gonna completely remove math.h
dependency, until it's
still use floor function, but it's look like for this case it could be done
easily. Just have to
compute some things, here is the problem, reading value of
`(int)((char*)&dd)[6]`  : 
Result      Read value > ...
1   |   -16
2   |   0
3   |   8
4   |   16
5   |   20
6   |   24
7   |   28
8   |   32
9   |   34
10  |   36
11  |   38
12  |   40
13  |   42
14  |   44
15  |   46

Befroe make a table i would like to find the calcul based solution, i things can
be nice to know in 
the future ;p.

---

**Comment by kevmuret** [comment]
this don't work for me : poi = 1 << (po << 4);

not yet updating code, because i need a lesson about bits, cause i don't know them well yet.

**Comment by snoopyjc** [comment]
In hex, 16 is 10, 16_16 is 100, 16_16_16 is 1000, etc.
In binary, 16 is 10000, 16_16 is 100000000, 16_16_16 is 1000000000000

Ok - sorry I made a mistake, the correct code should be:

```
poi = 1 << (po << 2);
```

po << 2 is the same as po \* 2**2, or po \* 4, but shift is faster than multiply.

1<<4 is 16, 1<<8 is 16_16, 1<<12 is 16_16_16. So 1<<(po<<2) is the same as
2__(po_4).

--joe

---- On Wed, 22 Oct 2014, kevmuret (notifications@github.com) wrote:

this don't work for me : poi = 1 << (po << 4);

not yet updating code, because i need a lesson about bits, cause i don't know
them well yet.

---

**Comment by kevmuret** [comment]
Thanks for your help ! I'm currently working on that, i'm gonna start thinking in shift :) for now.

**Comment by snoopyjc** [comment]
Ok cool!  Let me know if the rest of my proposed changes work! :-)

--joe

**Comment by kevmuret** [comment]
You can see by yourself, i updated the codes, looks like work good after some little mods, please read the codes and tell me if you've better optimizations, specially for the dechex() where i had to make the string starting at correct address, because the values where filled from the last char.

I also choose to keep the ishexchar() for people who are parsing non ascii documents and want to test if it's hexchar before make conversions. I just removed the pointer for limit memory fetches.

**Comment by snoopyjc** [comment]
Why don't you just return hex2 instead of copying it?
--joe

**Comment by kevmuret** [comment]
I'm just moving the characters at the begining of the memory allocated by malloc(), to be able to free() and in contrary something is wrong in my point of view. I will make another version without malloc call

**Comment by snoopyjc** [comment]
Oh - ok - yeah - I'm so used to Java I forgot about having to free.  Yes,
another version where
the user passes in an output buffer would be good.  You can also compute the
length of the output
string using a binary search as follows so you don't have to copy:

```
int len = 9;
if(value & 0xFFFF0000) {
    if(value & 0xFF000000) {
        if(value & 0xF0000000) {
              ;   // len already set
        } else {
              len = 8;
        }
    } else if(value & 0x00F00000) {
        len = 7;
    } else {
        len = 6;
    }
} else if(value & 0x0000FF00) {
    if(value & 0x0000F000) {
        len = 5;
    } else {
        len = 4;
    }
} else if(value & 0x000000FF) {
    if(value & 0x000000F0) {
        len = 3;
    } else {
        len = 2;
} else {
    len = 2;
}
```

---- On Thu, 23 Oct 2014, kevmuret (notifications@github.com) wrote:

I'm just moving the characters at the begining of the memory allocated by
malloc(), to be able to
free() and in contrary something is wrong in my point of view. I will make
another version without
malloc call 

---

**Comment by kevmuret** [comment]
I will add an argument for output and in case of NULL passed the size will calculated using your code.

**Comment by kevmuret** [comment]
I choose to add 3 arguments to dechex(), see the README for more details.
All things are now possible. Seems to be fast every time. But the fastest shoud be the ways i made it in hex.c and ascii.c

**Comment by snoopyjc** [comment]
Looking good!!!
--joe

---- On Fri, 24 Oct 2014, kevmuret (notifications@github.com) wrote:

I choose to add 3 arguments to dechex(), see the README for more details.
All things are now possible. Seems to be fast every time. But the fastest shoud
be the ways i made it
in hex.c and ascii.c

---
