### ISSUE TITLE
How to have result with constant length?

### ISSUE THREAD

**Issue by LeMoussel** [kevmuret/libhex#2]
I want to have a constant chain length
```
char*conv = NULL;
conv = dechex(rndNonce32, nonce32, 8);
std::cout << "nonce32:\n" << conv << std::endl;
```
If  `rndNonce32` = 1058279669, it's OK result is 3f1410f5 (strlen=8)
But with `rndNonce32 ` = 221868849, result is d397331 (strlen=7), shouldn't the result be 0d397331?

**Comment by kevmuret** [comment]
It’s up to you to pad your string.

Last parameter is treated as a boolean and is used to terminate the string with NULL bytes.

Sorry to a answer lately.
